// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7TVrvG_I9RQ9d5L4UB1MZtnx3uuJHfyY',
    appId: '1:69269192136:web:9ec0a0ff881ee9fa3c94fd',
    messagingSenderId: '69269192136',
    projectId: 'todo-fe42b',
    authDomain: 'todo-fe42b.firebaseapp.com',
    storageBucket: 'todo-fe42b.appspot.com',
    measurementId: 'G-XCX15VC74L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZRlyQPkJP3G-X7n8ZB88PQod-QOfwKGI',
    appId: '1:69269192136:android:9cd1ed44225b27f53c94fd',
    messagingSenderId: '69269192136',
    projectId: 'todo-fe42b',
    storageBucket: 'todo-fe42b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHGSuMWt306TTpnywMp83_NQjRwlgxMDE',
    appId: '1:69269192136:ios:77fdcf61aeb59e003c94fd',
    messagingSenderId: '69269192136',
    projectId: 'todo-fe42b',
    storageBucket: 'todo-fe42b.appspot.com',
    iosClientId: '69269192136-gcm33qovdhjfk1o8ovf1eqn97msl4ls8.apps.googleusercontent.com',
    iosBundleId: 'com.example.myProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHGSuMWt306TTpnywMp83_NQjRwlgxMDE',
    appId: '1:69269192136:ios:6514d5e402ea16c93c94fd',
    messagingSenderId: '69269192136',
    projectId: 'todo-fe42b',
    storageBucket: 'todo-fe42b.appspot.com',
    iosClientId: '69269192136-p2hrrkscohn15uvrh8fh2avrbk60m037.apps.googleusercontent.com',
    iosBundleId: 'com.example.myProject.RunnerTests',
  );
}
